name: Testing
'on': pull_request

env:
  FIREBASE_TOKEN: '${{secrets.FIREBASE_TOKEN}}'
  FRONTEND_SECRETS_PASSPHRASE: '${{secrets.FRONTEND_SECRETS_PASSPHRASE}}'
  FUNCTIONS_SECRETS_PASSPHRASE: '${{secrets.FUNCTIONS_SECRETS_PASSPHRASE}}'
jobs:
  development_build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo yarn global add firebase-tools
          sudo apt-get install xvfb
          yarn install
      - name: Decrypt Secrets
        run: yarn decrypt:ci
      - name: Running test
        run: 'yarn test && firebase emulators:exec \"yarn test:ci\"'
