name: Testing
'on': pull_request

env:
  FIREBASE_TOKEN: '${{secrets.FIREBASE_TOKEN}}'

jobs:
  development_build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo yarn global add firebase-tools
          sudo apt-get install xvfb
          yarn install
      - name: Build development
        run: 'yarn run build'
      - name: Running test
        run: 'yarn test'
