name: Deploying
'on':
  push:
    branches:
      - production
env:
  FIREBASE_TOKEN: '${{secrets.FIREBASE_TOKEN}}'
  FRONTEND_SECRETS_PASSPHRASE: '${{secrets.FRONTEND_SECRETS_PASSPHRASE}}'
  FUNCTIONS_SECRETS_PASSPHRASE: '${{secrets.FUNCTIONS_SECRETS_PASSPHRASE}}'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo yarn global add firebase-tools
          yarn install
      - name: Decrypt Secrets
        run: yarn decrypt:ci
      - name: Build development
        run: 'yarn run build'
      - name: Running test
        run: 'yarn test'
      - name: Deploy
        run: 'firebase deploy'
